INSERT INTO series (title, author_id, subgenre_id) VALUES ('Lord of the Rings', 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ('Lord of the Rings', 1, 1);
INSERT INTO books (title, year, series_id) VALUES ('Lord of the Rings, Book 1', 1988, 1);
INSERT INTO books (title, year, series_id) VALUES ('Lord of the Rings, Book 2', 1988, 1);
INSERT INTO books (title, year, series_id) VALUES ('Lord of the Rings, Book 3', 1988, 1);
INSERT INTO books (title, year, series_id) VALUES ('Lord of the Rings, Book 4', 1988, 1);
INSERT INTO books (title, year, series_id) VALUES ('Lord of the Rings, Book 5', 1988, 1);
INSERT INTO books (title, year, series_id) VALUES ('Lord of the Rings, Book 6', 1988, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ('Frodo', 'Hobbit', "Oh Sam.", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ('Sam', 'Hobbit', "Come on Mr. Frodo.", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ('Gandalf', 'Maia', "You shall not pass.", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ('Sauron', 'Maia', "evil gaze", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ('Aragorn', 'Dunedain', "...", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ('Elrond', 'Elf', "Fools", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ('Bilbo', 'Hobbit', "My old ring!", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ('Mouth of Sauron', "Man", 'Death', 1, 1);
INSERT INTO subgenres (name) VALUES ('Fantasy');
INSERT INTO subgenres (name) VALUES ('Horror');
INSERT INTO authors (name) VALUES ('JRR Tolkien');
INSERT INTO authors (name) VALUES ('George RR Martin');
INSERT INTO character_books (book_id, character_id) VALUES (1, 1);
INSERT INTO character_books (book_id, character_id) VALUES (2, 1);
INSERT INTO character_books (book_id, character_id) VALUES (3, 1);
INSERT INTO character_books (book_id, character_id) VALUES (4, 1);
INSERT INTO character_books (book_id, character_id) VALUES (5, 1);
INSERT INTO character_books (book_id, character_id) VALUES (6, 1);
INSERT INTO character_books (book_id, character_id) VALUES (1, 2);
INSERT INTO character_books (book_id, character_id) VALUES (2, 2);
INSERT INTO character_books (book_id, character_id) VALUES (3, 2);
INSERT INTO character_books (book_id, character_id) VALUES (4, 2);
INSERT INTO character_books (book_id, character_id) VALUES (5, 2);
INSERT INTO character_books (book_id, character_id) VALUES (6, 2);
INSERT INTO character_books (book_id, character_id) VALUES (1, 3);
INSERT INTO character_books (book_id, character_id) VALUES (2, 3);
INSERT INTO character_books (book_id, character_id) VALUES (3, 3);
INSERT INTO character_books (book_id, character_id) VALUES (4, 3);